# Logging
CONFIG_LOG=y

# Board support
CONFIG_DK_LIBRARY=y

# Modem
CONFIG_NRF_MODEM_LIB=y
CONFIG_LTE_LINK_CONTROL=y
CONFIG_MODEM_INFO=y

# Networking
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_UDP=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_SOCKETS_OFFLOAD=y
CONFIG_DNS_RESOLVER=y
CONFIG_POSIX_API=y

# Zephyr native CoAP
CONFIG_COAP=y

CONFIG_HEAP_MEM_POOL_SIZE=1032
CONFIG_MAIN_STACK_SIZE=2048
